sklearn_classifier/sklearn_classifier.py

for clarity, changed x_label and y_label to fpr_label and tpr_label

fix variable in plot_roc for train function

---

test_classifier/test_classifier.py

for clarity, changed x_label and y_label to fpr_label and tpr_label

fix variable name plot_roc

---

send_email/README.md
send_email/function.yaml
send_email/send_email.ipynb

Created a function to send emails using SMTP, allowing sending artifacts as well as other arbitrary text/attachments.

Add send-email function

---

project_runner/function.yaml
project_runner/project_runner.ipynb

A Nuclio based project - workflow runner

Project runner

---

model_server/model_server.ipynb

Building json of list of instances, and sending it to the model server to test the prediction
This is needed as users were not sure what to send to the model server

Add a test to the model server - sending curl with data for predict

---

cli/test_suite.py

adding multi process support for tetsing

add multiprocessing support

---

.github/workflows/test-all.yaml

update test-all ci 

---

arc_to_parquet/test_arc_to_parquet.py
feature_perms/feature_perms.py
feature_perms/requierments.txt
feature_perms/tets_feature_perms.py

Feature perms

---

rnn_serving/function.yaml
rnn_serving/item.yaml
rnn_serving/rnn_serving.ipynb

rnn_serving update image name

---

xgb_trainer/xgb_trainer.ipynb

update xgb_tainer notebook remove code from the notebook

update xgb_tainer notebook

---

aggregate/test_aggregate.py

DEVOPS-319 test commit

---

aggregate/test_aggregate.py

DEVOPS-319 test ci

---

cli/item_to_function.py

- Added `extra_spec` to `item_to_function.py`

[cli] Updated item_to_function

---

azureml_utils/function.yaml
azureml_utils/item.yaml

- Added fields in spec.build:  `with_mlrun: True`, `auto_build: true`
- Added fiels in spec: `allow_empty_resources: True`

[azureml_utils] Updated build configuration

---

azureml_utils/function.yaml
azureml_utils/item.yaml
azureml_utils/requirements.txt

- Added `plotly` to image in `item.yaml`, `function.yaml` and in `requirements.txt`. In order to get `parallel_coordinates` in the `outputs`.

[azureml_utils] Added plotly to image

---

ingest/test_ingest.py

[ingest] fixed test

---

cli/helpers.py
cli/marketplace/build.py
cli/marketplace/conf.template
cli/test_suite.py
requirements.txt

- Encoding type for html corrected to `UTF-8`.
- Requirements collecting parsed to be without version constraints.
- `Sphinx` requirements updated as well.

[marketplace-build] Fixed requirements collecting for sphinx autodoc

---

cli/test_suite.py

- `get_item_yaml_values()` handling in `test_suite.py`

[marketplace-build] fixed bug

---

auto_trainer/item.yaml

`auto_trainer` function version increased to `0.10.0`

[Marketplace-build] test build on auto-trainer

---

auto_trainer/item.yaml
cli/marketplace/build.py
concept_drift/item.yaml
concept_drift/requirements.txt
concept_drift_streaming/item.yaml
concept_drift_streaming/requirements.txt
model_monitoring_batch/item.yaml
model_monitoring_batch/requirements.txt
model_monitoring_stream/item.yaml
model_monitoring_stream/requirements.txt
requirements.txt
sql_to_file/item.yaml
sql_to_file/requirements.txt

- Removed download option from documentation (`.rst` file)
- Added necessary requirements files for missing functions.
- Removed `mlrun` from building requirements
- Updated function versions for the related functions + `auto_trainer` for testing.

[Marketplace-build] updated build requirements

---

requirements.txt

[Marketplace-build] Updated requirements

---

cli/marketplace/build.py

- Added new version to `catalog.json` in building process

[Marketplace-build] Added new version to catalog.json

---

cli/helpers.py
cli/marketplace/build.py

- `get_mock_requirements` - function for collecting mock requirements for documentation from all the functions

[Marketplace-Build] requirement collection for docs via .py files

---

cli/helpers.py
cli/marketplace/build.py

- Corrected removing download from documentation
- Removed redundant functions from `helpers.py`

[Marketplace-build]  removing download option from doc page fixed

---

azureml_utils/function.yaml
azureml_utils/item.yaml

Changed versions of `azureml-core` and `azureml-train-automl-client` from `1.33.0` to `1.40.0` .

[Azureml_utils] Updated versions of azureml packages

---

snowflake_dask/item.yaml
snowflake_dask/requirements.txt
snowflake_dask/test_snowflake_dask.py

during my last pr, noticed that missing mlrun in the requirements.txt, added in, redo the pr

fix the unit test

---

cli/helpers.py
cli/test_suite.py
rnn_serving/requirements.txt

[rnn_serving] fixed version for tensorflow in requirements.txt

---

auto_trainer/item.yaml
churn_server/item.yaml
coxph_test/item.yaml
feature_perms/item.yaml
get_offline_features/item.yaml
model_server/item.yaml
model_server_tester/item.yaml
rnn_serving/item.yaml
sklearn_classifier/item.yaml
test_classifier/item.yaml
v2_model_server/item.yaml
xgb_serving/item.yaml
xgb_test/item.yaml
xgb_trainer/item.yaml

Updated missing docs functions version to create new docs.

[Docs] update function version to functions with missing docs

---

gen_class_data/test_gen_class_data.py

- Fixed `gen_class_data` artifact path check

[MLRun 1.1.0 compatibility]

---

aggregate/test_aggregate.py
gen_class_data/test_gen_class_data.py

fixed tests assertions of `aggregate` and `gen_class_data` functions

[MLRun 1.1.0 compatibility] 

---

onnx_utils/onnx_utils.py

[onnx_utils] Updated code for mlrun 1.1.0

---

.github/workflows/test-all.yaml

DEVOPS-425 point action to app user

DEVOPS-425 point action to app user

---

requirements.txt

updated sphinx version to `4.0.2`

[Build] Update sphinx version

---

requirements.txt

Updated sphinx-book-theme to `0.3.3`

[Build] updated sphinx-book-theme

---

requirements.txt

Revert unnecessary pull request

---

sklearn_classifier/item.yaml

[Testing] hide sklearn classifier from dev channel - UI

---

sklearn_classifier/item.yaml

[Test] test hidden flag restore

---

.github/workflows/ci.yaml

update ci k8s version

---

auto_trainer/requirements.txt
coxph_trainer/requirements.txt
describe_dask/requirements.txt
feature_perms/requirements.txt
sklearn_classifier/requirements.txt
test_classifier/requirements.txt
xgb_custom/requirements.txt
xgb_serving/requirements.txt
xgb_trainer/requirements.txt

Replace `sklearn` in requirements to `scikit-learn`

[Tests] fix CI test-py failing on installing sklearn

---

bert_embeddings/bert_embeddings.ipynb
bert_embeddings/item.yaml

Remove project name `"function-marketplace"` from deploy (project is not even created in notebook).
Also removed `!align_mlrun` cell.
[ML-3080](https://jira.iguazeng.com/browse/ML-3080)

[Bert-Embedding] Fix example notebook

---

cli/marketplace/build.py

Added relative assets to `catalog.json`:
`item["example"]` -> `src/item["example"]`
`item["spec"]["filename"]` -> `src/item["spec"]["filename"]`
`item["docs"]` -> `static/documentation.html`

[Build] Add relative assets to catalogs

---

.github/workflows/ci.yaml
.github/workflows/test-all.yaml
cli/helpers.py

This reverts commit 0cd1f1585a618c253f201b6f5a63502cdbddb591.

Revert "[Build] Update python version in CI (#620)"

---

cli/helpers.py

Revert "[Build] Install python 3.9 when testing"

---

.github/workflows/test-all.yaml
cli/helpers.py

Revert "[CI] Upgrade tests to python 3.8"

---

cli/test_suite.py

+ also applied black and isort

[CI] Ignore failed requirements installation on tests

---

cli/test_suite.py

Revert "[CI] Ignore failed requirements installation on tests"

---

xgb_serving/function.yaml
xgb_serving/item.yaml
xgb_serving/requirements.txt
xgb_serving/test_xgb_serving.py
xgb_serving/xgb_serving.py

update function to use v2_model_server 
update valid test

[xgb-serving] update function and tests

---

cli/item_to_function.py

In the changes of adding the `-b` flag, a bug was introduced that fails running it on a folder.

Fix item-to-function bug

---

azureml_utils/item.yaml
cli/test_suite.py
feature_perms/item.yaml
pii_recognizer/item.yaml
sentiment_analysis_serving/item.yaml
transcribe/item.yaml

adding a valid test attribute for item yaml will disable failing tests until they work

[Testing] add valid test attribute to item yaml 

---

.github/workflows/ci.yaml
.github/workflows/test-all.yaml

change continue-on-error to false

[cli] update checkout version from v2 to v3

---

transcribe/test_transcribe.py

Fixed only test - no need to update function.

[transcribe] Fixed test

---

batch_inference/item.yaml

[ML-4969](https://jira.iguazeng.com/browse/ML-4969)

Bump batch_inference version following pr 736

---

auto_trainer/function.yaml
auto_trainer/item.yaml
cli/item_to_function.py
structured_data_generator/function.yaml
structured_data_generator/item.yaml

[ML-5418](https://jira.iguazeng.com/browse/ML-5418)

Remove state_thresholds from function.yaml of auto_trainer and structured_data_generator

---

requirements.txt

Restrict packages that requires sphinx v5.0

[Build] restrict sphinxcontrib packages

---

.github/workflows/test-all.yaml

Iguazio-cicd user token updated in repo secrets:
https://github.com/mlrun/functions/settings/secrets/actions MARKETPLACE_ACCESS_TOKEN_V3
new token gh...Zmf was set around April

Iguazio-cicd user token updated

---

.github/workflows/test-all.yaml

forcing iguazio-cicd to deal with Author identity unknown

forcing iguazio-cicd auth

---

cli/marketplace/_static/css/custom.css
cli/marketplace/build.py
cli/marketplace/conf.template

Resolves https://iguazio.atlassian.net/browse/FHUB-22

update sphinx theme

---

requirements.txt

https://iguazio.atlassian.net/browse/FHUB-70

[black] Black vulnerable to Regular Expression Denial of Service (ReDoS)e

---

mlflow_utils/item.yaml
mlflow_utils/requirements.txt

cherry pick:
- #865 
https://iguazio.atlassian.net/browse/FHUB-68

[mlflow_utils] update mlflow version (#865)

---

cli/marketplace/build.py

Revert "[UI] functions pages are broken "

---

functions/src/azureml_utils/item.yaml
functions/src/azureml_utils/requirements.txt
functions/src/describe/requirements.txt
functions/src/mlflow_utils/item.yaml
functions/src/mlflow_utils/requirements.txt
functions/src/onnx_utils/item.yaml
functions/src/onnx_utils/requirements.txt

Cherry Pick for:
- #890 
- #891 
- #892 
- #893

Cherry pick vulnerabilities issues 

---

modules/src/count_events/count_events.ipynb
modules/src/count_events/count_events.py
modules/src/count_events/item.yaml
modules/src/count_events/requirements.txt
modules/src/count_events/test_count_events.py

[Count Events] Add count events module

---

functions/src/open_archive/open_archive.py

Add AWS_ENDPOINT_URL_S3 in addition to S3_ENDPOINT_URL (#901)
